---
title: "Simulation"
author: "Lei Shi"
date: "2022-11-23"
output: pdf_document
---

```{r setup, include=FALSE}
library("dplyr")
options(dplyr.summarise.inform = FALSE)
library("latex2exp")
library("ggplot2")
library("tidyverse")
if(!require("AlgDesign")){
  install.packages("AlgDesign")
  library("AlgDesign")
}
library("car")
library("glmnet")
source("/Users/leishi/Desktop/Research/ForwardScreening/auxillary_functions.R")
```



1. Determine the factorial effect sizes.
```{r}
N0_choice = c(seq(2, 10, by = 2), 15, 20)
for (N0 in N0_choice[c(6,7)]){
  # basic parameter setup
  K = 8
  num_trt_group = 2^K
  trt_group_size = rep(N0, 2^K)
  num_pop = sum(trt_group_size)
  level = K
  
  
  design.core <- factor.design(K, trt_group_size = rep(1,2^K), interaction = level, centering = 1/2)
  data.ind <- factor.design(K, trt_group_size = trt_group_size, 1)
  design.run <- factor.design(K, trt_group_size = trt_group_size, interaction = level, centering = 1/2)
  
  # seed 
  set.seed(2022)
  tau = rep(0, sum(choose(K,0:level)))
  tau[1] = runif(choose(K,0), 0.044*5, 10*0.044) * sign(runif(choose(K,0),-1, 1))
  tau[(sum(choose(K,0:0))+1):sum(choose(K,0:1))] = 0.20 * sign(runif(choose(K,1),-1, 1))
  tau[(sum(choose(K,0:1))+1):sum(choose(K,0:2))] = 0.10 * sign(runif(choose(K,2),-1, 1))
  #runif(choose(K,2), 0.044*4, 5*0.044) * sign(runif(choose(K,2),-1, 1)) * rbinom(choose(K,2), 1, 0.7)
  
  #tau <- c(
  #  runif(choose(K,0), 0.044*5, 10*0.044) * sign(runif(choose(K,0),-1, 1)),
  #  runif(choose(K,1), 0.044*5, 10*0.044) * sign(runif(choose(K,1),-1, 1)),
  #  runif(choose(K,2), 0.044*1, 5*0.044) * sign(runif(choose(K,2),-1, 1)) * rbinom(choose(K,2), 1, 0.7),
  #)
  
  
  # effects
  names(tau) <- c("(Intecept)", names(design.core))
  
  # non-zeros
  nonzero.effect <- paste0("F", 1:5)
  nonzero.effect <- c(nonzero.effect, 
                      heredity.proceed.new(K, nonzero.effect, 1,
                                           "strong")$working_model)
  zero.effect <- setdiff(names(tau), nonzero.effect)
  tau[zero.effect] <- 0
  nonzero.effect = names(tau[abs(tau)>1e-6])
  
  # seed = 2022
  # tau <- c(0.000000,  4.263911, -3.589037,  1.481314, 0.000000, 0.000000, -1.297196, 0.000000, 2.481268, 0.000000,  1.007448,  0.000000,  1.578967, -3.077587, -3.437906, rep(0, 2^K-1-15))
  
  #tau
  mu <- as.matrix(design.core) %*% (tau[2:length(tau)])
  
  finite.pop.opts <- list()
  
  # finite.pop initialization
  #finite.pop.opts$dist <- rep("norm", 2^K)
  #finite.pop.opts$avg  <- mu
  #finite.pop.opts$std  <- rep(1, 2^K)
  
  finite.pop.opts$dist <- rep("exp", 2^K)
  finite.pop.opts$mu  <- mu
  finite.pop.opts$rate  <- rep(1, 2^K)
  finite.pop.init <- list(
    num_pop = num_pop,
    num_trt_group = num_trt_group,
    finite.pop.opts = finite.pop.opts
  )
  
  # generate a finite population
  pop_1 <- finite.pop(num_pop, num_trt_group, finite.pop.opts)
  
  # factorial.data opts
  factorial.data.opts <- list()
  
  # factorial.data init
  factorial.data.init <- list(
    num_factors = K,
    trt_group_size = trt_group_size,
    pop = pop_1,
    factorial.data.opts = factorial.data.opts,
    finite.pop.init = list()
  )
  
  factorial_data_raw <- factorial.data(K, trt_group_size, pop = pop_1,
                                       factorial.data.opts, finite.pop.init)
  
  factorial_data <- factorial_data_raw$factorial_data
  
  #
  alpha.vec <- rep(0.10/level, level)

  if (FALSE){
    simulation.res.strong <- comb.select.trial(factorial.data.init, 
                                        alpha.vec = alpha.vec, 
                                        level = level, 
                                        design.run, design.core,
                                        Niter = 500, num.ties = 1)
  
    saveRDS(simulation.res.strong, paste0("simulation_large_effects_N0_", N0, ".rds"))
  }
  
}

```


```{r fig.height=8, fig.width=10}
N0_choice = c(seq(2, 12, by = 2), 15, 20)
model_report = list()
coverage_report = list()

for (N0_ind in 1:8){
  N0 = N0_choice[N0_ind]
  # basic parameter setup
  K = 8
  num_trt_group = 2^K
  trt_group_size = rep(N0, 2^K)
  num_pop = sum(trt_group_size)
  level = K
  
  
  design.core <- factor.design(K, trt_group_size = rep(1,2^K), interaction = level, centering = 1/2)
  data.ind <- factor.design(K, trt_group_size = trt_group_size, 1)
  design.run <- factor.design(K, trt_group_size = trt_group_size, interaction = level, centering = 1/2)
  
  # seed 
  set.seed(2022)
  tau = rep(0, sum(choose(K,0:level)))
  tau[1] = runif(choose(K,0), 0.044*5, 10*0.044) * sign(runif(choose(K,0),-1, 1))
  tau[(sum(choose(K,0:0))+1):sum(choose(K,0:1))] = 0.20 * sign(runif(choose(K,1),-1, 1))
  tau[(sum(choose(K,0:1))+1):sum(choose(K,0:2))] = 0.10 * sign(runif(choose(K,2),-1, 1))
  #runif(choose(K,2), 0.044*4, 5*0.044) * sign(runif(choose(K,2),-1, 1)) * rbinom(choose(K,2), 1, 0.7)
  
  #tau <- c(
  #  runif(choose(K,0), 0.044*5, 10*0.044) * sign(runif(choose(K,0),-1, 1)),
  #  runif(choose(K,1), 0.044*5, 10*0.044) * sign(runif(choose(K,1),-1, 1)),
  #  runif(choose(K,2), 0.044*1, 5*0.044) * sign(runif(choose(K,2),-1, 1)) * rbinom(choose(K,2), 1, 0.7),
  #)
  
  
  # effects
  names(tau) <- c("(Intecept)", names(design.core))
  
  # non-zeros
  nonzero.effect <- paste0("F", 1:5)
  nonzero.effect <- c(nonzero.effect, 
                      heredity.proceed.new(K, nonzero.effect, 1,
                                           "strong")$working_model)
  zero.effect <- setdiff(names(tau), nonzero.effect)
  tau[zero.effect] <- 0
  nonzero.effect = names(tau[abs(tau)>1e-6])
  
  # seed = 2022
  # tau <- c(0.000000,  4.263911, -3.589037,  1.481314, 0.000000, 0.000000, -1.297196, 0.000000, 2.481268, 0.000000,  1.007448,  0.000000,  1.578967, -3.077587, -3.437906, rep(0, 2^K-1-15))
  
  #tau
  mu <- as.matrix(design.core) %*% (tau[2:length(tau)])
  
  finite.pop.opts <- list()
  
  # finite.pop initialization
  #finite.pop.opts$dist <- rep("norm", 2^K)
  #finite.pop.opts$avg  <- mu
  #finite.pop.opts$std  <- rep(1, 2^K)
  
  finite.pop.opts$dist <- rep("exp", 2^K)
  finite.pop.opts$mu  <- mu
  finite.pop.opts$rate  <- rep(1, 2^K)
  finite.pop.init <- list(
    num_pop = num_pop,
    num_trt_group = num_trt_group,
    finite.pop.opts = finite.pop.opts
  )
  
  # generate a finite population
  pop_1 <- finite.pop(num_pop, num_trt_group, finite.pop.opts)
  
  # factorial.data opts
  factorial.data.opts <- list()
  
  # factorial.data init
  factorial.data.init <- list(
    num_factors = K,
    trt_group_size = trt_group_size,
    pop = pop_1,
    factorial.data.opts = factorial.data.opts,
    finite.pop.init = list()
  )
  
  factorial_data_raw <- factorial.data(K, trt_group_size, pop = pop_1,
                                       factorial.data.opts, finite.pop.init)
  
  factorial_data <- factorial_data_raw$factorial_data
  
  #
  alpha.vec <- rep(0.10/level, level)

  simulation.res.strong = readRDS(paste0("simulation_large_effects_N0_", N0, ".rds"))
  
  model_report[[N0_ind]] = check.model.selection(simulation.res.strong$model.select.res, nonzero.effect)
  
  # target_weight = design.core$F1/num_trt_group
  mu_pop = factorial_data_raw$subgroup.effect
  
  target_weight = rep(0, num_trt_group)
#  target_weight[1] = -1
#  target_weight[2^K-1] = 1
  target_weight[2^K] = 1
  true_effect = sum(target_weight * mu_pop)
  
  coverage_report[[N0_ind]] = check.target.coverage(simulation.res.strong, 
                        design.core, 
                        target_weight, true_effect)
}
```




4. report results

```{r}
model_report_df = data.frame(
  selection = c(model_report[[1]][,1], model_report[[2]][,1], model_report[[3]][,1], 
                model_report[[4]][,1], model_report[[5]][,1], model_report[[6]][,1], 
                model_report[[7]][,1], model_report[[8]][,1])/500,
  N0 = c(rep(N0_choice[1], 8), rep(N0_choice[2], 8), rep(N0_choice[3], 8), 
           rep(N0_choice[4], 8), rep(N0_choice[5], 8), rep(N0_choice[6], 8), 
           rep(N0_choice[7], 8), rep(N0_choice[8], 8)), 
  Method = c(rep(c("FB", "WB", "Forward Bonferroni", "FL", "WL", 
                   "Forward Lasso", "Naive Bonferroni", "Naive Lasso"), 8))
)

rejection_report_df = data.frame(
  Rejection = c(coverage_report[[1]][,4], coverage_report[[2]][,4], coverage_report[[3]][,4], 
                coverage_report[[4]][,4], coverage_report[[5]][,4], coverage_report[[6]][,4],
                coverage_report[[7]][,4], coverage_report[[8]][,4]),
  N0 = c(rep(N0_choice[1], 9), rep(N0_choice[2], 9), rep(N0_choice[3], 9), 
         rep(N0_choice[4], 9), rep(N0_choice[5], 9), rep(N0_choice[6], 9),
         rep(N0_choice[7], 9), rep(N0_choice[8], 9)), 
  Method = c(rep(c("FB", "WB", "Forward Bonferroni", "FL", "WL", 
                   "Forward Lasso", "Naive Bonferroni", "Naive Lasso", "No Selection"), 8))
)

coverage_report_df = data.frame(
  coverage = c(coverage_report[[1]][,3], coverage_report[[2]][,3], coverage_report[[3]][,3], 
               coverage_report[[4]][,3], coverage_report[[5]][,3], coverage_report[[6]][,3],
               coverage_report[[7]][,3], coverage_report[[8]][,3]),
  N0 = c(rep(N0_choice[1], 9), rep(N0_choice[2], 9), rep(N0_choice[3], 9), 
           rep(N0_choice[4], 9), rep(N0_choice[5], 9), rep(N0_choice[6], 9), 
           rep(N0_choice[7], 9), rep(N0_choice[8], 9)), 
  Method = c(rep(c("FB", "WB", "Forward Bonferroni", "FL", "WL", 
                   "Forward Lasso", "Naive Bonferroni", "Naive Lasso", "No Selection"), 8))
)




combined_report = merge(model_report_df, rejection_report_df,  by = c("N0", "Method"))
combined_report = merge(combined_report, coverage_report_df, by = c("N0", "Method"))
# View(combined_report)
```


```{r}


target_weight = rep(0, num_trt_group)
target_weight[1] = -1
target_weight[2^K-1] = 1
t(as.matrix(cbind(1, design.core))) %*% target_weight

```




```{r fig.height=2, fig.width=3}
plot_selection = ggplot(combined_report %>% filter(!Method %in% c("FB", "FL", "WB", "WL")), 
       aes(x=N0, y=selection, col = Method, lty = Method, pch = Method)) +
  geom_line(size = 1) + 
  geom_point(size = 3) + 
  geom_hline(yintercept = 1, lty = 2) +
  labs(x = TeX("$N_0$"), y = "Perfect selection probability") + 
  theme_classic(base_size = 20)

plot_selection
```





```{r fig.height=2, fig.width=3}
plot_rejection = ggplot(combined_report %>% filter(!Method %in% c("FB", "FL", "WB", "WL", "No Selection")), 
       aes(x=N0, y=Rejection, col = Method, lty = Method, pch = Method)) +
  geom_line(size = 1) + 
  geom_point(size = 3) + 
  geom_hline(yintercept = 1, lty = 2) +
  labs(x = TeX("$N_0$"), y = "Power") + 
  theme_classic(base_size = 20)

plot_rejection
```



```{r fig.height=2, fig.width=3}
plot_coverage = ggplot(combined_report %>% filter(!Method %in% c("FB", "FL", "WB", "WL", "No Selection")), 
       aes(x=N0, y=coverage, col = Method, lty = Method, pch = Method)) +
  geom_line(size = 1) + 
  geom_point(size = 3) + 
  geom_hline(yintercept = 0.95, lty = 2) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1), limits = c(0.3, 1)) +
  labs(x = TeX("$N_0$"), y = "Coverage probability") + 
  theme_classic(base_size = 20)
plot_coverage
```


```{r}
ggsave("plot_selection.png", width = 8, height = 6, units = "in", plot_selection)
ggsave("plot_rejection.png", width = 8, height = 6, units = "in", plot_rejection)
ggsave("plot_coverage.png", width = 8, height = 6, units = "in", plot_coverage)
plot_selection
plot_rejection
plot_coverage

combined_plot = ggarrange(plot_selection, 
          plot_rejection,
          plot_coverage,
         common.legend = TRUE, nrow = 1)
combined_plot

ggsave("combined_plot_N0.pdf", width = 15, height = 5, units = "in", combined_plot)
```

```{r}
power_coverage_report = merge(rejection_report_df, coverage_report_df, by = c("N0", "Method"))
# View(combined_report)
```


```{r}
plot_rejection_no_selection = ggplot(power_coverage_report %>% filter(Method %in% c("Forward Bonferroni", "No Selection")), 
       aes(x=N0, y=Rejection, col = Method, lty = Method, pch = Method)) +
  geom_line(size = 1) + 
  geom_point(size = 3) + 
  geom_hline(yintercept = 1.0, lty = 2) +
#  scale_y_continuous(breaks = seq(0, 1, by = 0.1), limits = c(0.3, 1)) +
  labs(x = TeX("$N_0$"), y = "Power") + 
  theme_classic(base_size = 20) #+
#  scale_x_continuous(limits = c(0.26, 1.15))

plot_rejection_no_selection
```


```{r}
plot_coverage_no_selection = ggplot(power_coverage_report %>% filter(Method %in% c("Forward Bonferroni", "No Selection")), 
       aes(x=N0, y=coverage, col = Method, lty = Method, pch = Method)) +
  geom_line(size = 1) + 
  geom_point(size = 3) + 
  geom_hline(yintercept = 0.95, lty = 2) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1), limits = c(0.5, 1)) +
  labs(x = TeX("$N_0$"), y = "Coverage probability") + 
  theme_classic(base_size = 20) #+
#  scale_x_continuous(limits = c(0.26, 1.15))

plot_coverage_no_selection
```

```{r} 
ggsave("plot_rejection_test_N0.png", width = 8, height = 6, units = "in", plot_rejection_no_selection)
ggsave("plot_coverage_test_N0.png", width = 8, height = 6, units = "in", plot_coverage_no_selection)

combined_plot_test = ggarrange(plot_rejection_no_selection, 
          plot_coverage_no_selection,
         common.legend = TRUE, nrow = 1)
combined_plot_test

ggsave("combined_plot_test_N0.pdf", width = 10, height = 5, units = "in", combined_plot_test)
```


